project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"
    # - "!Results/"
    
date: last-modified
    
# Website configuration
website:
  title: "am-lh"
  site-url: https://am-lh.github.io/
  favicon: images/logoMP5.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Melting_pot.qmd
        text: Melting Pot
      - href: Side_projects.qmd
        text: Side Projects
  page-footer: 
    # background: light
    left: 
      - "Copyright 2023, Amélie Lehuen"
      - text: CC BY-SA 4.0
        href: https://creativecommons.org/licenses/by-sa/4.0/
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/amélie-lehuen-5262bb143/
      - icon: github
        href: https://github.com/am-lh
      - icon: twitter
        href: https://twitter.com/PennyOakLh
      - text: ResearchGate
        href: https://www.researchgate.net/profile/Amelie-Lehuen
      - text: Orcid
        href: https://orcid.org/my-orcid?orcid=0000-0002-3150-687
        
# general format parameters
toc: true # table of content at beginning of document
toc-location: left
toc-depth: 3
toc_float: TRUE
number-sections: true
highlight-style: pygments
bibliography: references.bib
        
# specific format parameters
format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    css: styles.css
    embed-resources: true
    self-contained-math: true
    html-math-method: katex # displays equations
    toc: true
    code-fold: true
    # mainfont: Nunito
    # enable banner style title blocks (see https://quarto.org/docs/authoring/title-blocks.html)
    title-block-banner: images/photo-vasière.jpg

  # docx: 
  #   reference-doc: Manuscripts/customreference_nonb.docx
  #   
  # pdf:
  #   code-line-numbers: true
  #   geometry: 
  #     - top=20mm
  #     - left=20mm 

# Execution parameters
editor: source
engine: knitr
execute:
  freeze: auto  # re-render only when source changes
  eval: true
  echo: false
  message: false
  warning: false
  output: true
  include: false
editor_options: 
  chunk_output_type: console
