project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "am-lh"
  site-url: https://am-lh.github.io/
  favicon: images/noun_shell_2156166.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Melting_pot.qmd
        text: Melting Pot
      - href: Side_projects.qmd
        text: Side Projects
  page-footer: 
    # background: light
    left: 
      - "Copyright 2023, Amélie Lehuen"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/amélie-lehuen-5262bb143/
      - icon: github
        href: https://github.com/am-lh
      - icon: twitter
        href: https://twitter.com/PennyOakLh
      - text: ResearchGate
        href: https://www.researchgate.net/profile/Amelie-Lehuen
      - text: Orcid
        href: https://orcid.org/my-orcid?orcid=0000-0002-3150-687
        
format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    toc: true
    embed-resources: true
    code-fold: false
    html-math-method: katex # displays equations
    css: styles.css
    # mainfont: Nunito

  
editor: visual

