project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "am-lh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    toc: true
    embed-resources: true
    code-fold: false
    html-math-method: katex # displays equations
    css: styles.css
    page-layout: full

execute:
  freeze: auto  # re-render only when source changes
  


